INTELSDK-2548 Fix docs problem in 24.8.0
euc-dev/ws1-sdk-intelligence pull request #11
Opened 2024-11-11 22:23 UTC by WWSellers

mkdocs.yml
- added missing entry to navigation: 'Enabling Telemetry Features in IntelligenceSDK for iOS'
- removed unneeded entry: 'Tune Workspace ONE Intelligence SDK for iOS Logging'
(file is duplicate of WS1Intelligence.md)
- added missing entry to navigation: 'Telemetry Privacy Configuration'

ios-enable-telemetry-features-in-intelsdk.md
- added page title as header 1 in the page content to prevent confusion
- changed the other header level 1 lines to header level 2

ios-privacy-config.md
- corrected title to add "for iOS" 
- change redundant section header to header level 1 for the page

ios-tune-logging.md
- deleted file as a duplicate of ws1intelligence.md

ws1intelligence.md
- set 'toc' to show (added the # under the 'hide' metadata table entry)
    this will make an MkDocs-native table of contents show to the right of the content    
- removed [TOC] since it will be redundant. And some of the content can be shown at the top instead of having [TOC] use a lot of space at the top. 
- added blank line after 'See Also' so the list below it will be interpreted as unordered list.

2024-11-11 22:31 UTC, helmlingp commented on docs/Apple/ios-privacy-config.md
if you want 'Telemetry Privacy Configuration for iOS' as the main heading, then set it in the metadata section above as title rather than here

2024-11-11 22:31 UTC, helmlingp commented on docs/Apple/ios-tune-logging.md
if you want 'Telemetry Privacy Configuration for iOS' as the main heading, then set it in the metadata section above as title rather than here

2024-11-11 22:32 UTC, helmlingp requested changes
comments re headings

2024-11-11 22:49 UTC, Niranjan-B approved these changes

2024-11-11 23:51 UTC, WWSellers commented on docs/Apple/ios-tune-logging.md
we are removing this file, so it does not matter

2024-11-11 23:57 UTC, WWSellers commented on docs/Apple/ios-privacy-config.md
Done

2024-11-12 00:18 UTC, helmlingp approved these changes

2024-11-12 00:19 UTC, merged